name: Run Test

on:
  push:
    branches: [ "develop" ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.4.app

    - name: Use dummy GoogleService-Info.plist
      run: cp .github/ci/GoogleService-Info-dummy.plist ThankYouList/Resources/GoogleService-Info.plist

    - name: Allow plugin execution for Rswift
      run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

    - name: Install Bundler dependencies
      run: bundle install

    - name: Install CocoaPods dependencies
      run: bundle exec pod install
    
    - name: Build and test with Xcode
      env:
        CI: "true"
      run: |
          export CI=true
          xcodebuild -workspace ThankYouList.xcworkspace \
                     -scheme ThankYouListTests \
                     -destination 'platform=iOS Simulator,OS=18.5,name=iPhone 16' \
                     -skipPackagePluginValidation \
                     build test
