name: Run Test

on:
  push:
    branches: [ "develop" ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install CocoaPods dependencies
      run: bundle exec pod install
    
    - name: Build and test with Xcode
      run: |
          xcodebuild -workspace ThankYouList.xcworkspace \
                     -scheme ThankYouListTests \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14' \
                     build test
