name: Run Test

on:
  push:
    branches: [ "develop" ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.4.app

    - name: Install Bundler dependencies
      run: bundle install

    - name: Install CocoaPods dependencies
      run: bundle exec pod install
    
    - name: Build and test with Xcode
      run: |
          xcodebuild -workspace ThankYouList.xcworkspace \
                     -scheme ThankYouListTests \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 16' \
                     build test
